### ISSUE TITLE
[IMPROVE] Make test coverage 100%

### ISSUE THREAD

**Issue by 3jins** [3jins/blog-renewal#64]
Inspired by https://www.youtube.com/watch?v=jdlBu2vFv58

- [x] Measure the test coverage. (#65)
- [x] Solve conflicts among modules that use external connection like routers and repositories when they are run altogether.
  - Try [mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server)
- [x] Automate coverage assessment with [CI/CD system](https://github.com/3jins/blog-renewal/issues/49).
- [x] Raise test coverage to 100% with sustainable and practical method. (#97)
- [x] It seems branch coverage is not accurate. Branch coverage 100% can be achieved without testing all cases. It's necessary to check about it.
  - 'Branch coverage' is different with 'condition coverage'. Branch coverage only checks if both `if` and `else` cases are covered unlike condition coverage checks all detail conditions.
    - ex) `if (x > 0 && y > 0 && z > 0)`
    - branch coverage: covers 2 cases: `x > 0 && y > 0 && z > 0` is satisfied or not
    - condition coverage: covers 8 cases: `x > 0`/`x <= 0` *  `y > 0`/`y <= 0` *  `z > 0`/`z <= 0`
